# Generated by Django 6.0.4 on 2026-04-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_rated',
            field=models.BooleanField(default=False, verbose_name='هل تم تقييم المستخدم'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True, verbose_name='مستوى المستخدم'),
        ),
    ]
