# Generated by Django 4.2 on 2025-12-17 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='معرف المشروع')),
                ('title', models.CharField(help_text='أدخل عنواناً واضحاً ومعبراً للمشروع', max_length=200, verbose_name='عنوان المشروع')),
                ('description', models.TextField(help_text='أدخل وصفاً مفصلاً للمشروع وأهدافه', verbose_name='وصف المشروع')),
                ('requirements', models.TextField(blank=True, help_text='متطلبات إنجاز المشروع (المهارات المطلوبة، المعرفة السابقة)', verbose_name='المتطلبات')),
                ('objectives', models.TextField(blank=True, help_text='الأهداف التي سيحققها الطالب بعد إكمال المشروع', verbose_name='الأهداف التعليمية')),
                ('resources', models.TextField(blank=True, help_text='الموارد والمراجع المطلوبة لإنجاز المشروع', verbose_name='الموارد')),
                ('estimated_time', models.IntegerField(help_text='الوقت المقدر لإنجاز المشروع بالساعات', verbose_name='الوقت المقدر (بالساعات)')),
                ('level', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم'), ('expert', 'خبير')], help_text='مستوى صعوبة المشروع', max_length=20, verbose_name='المستوى')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('csharp', 'C#'), ('cpp', 'C++'), ('php', 'PHP'), ('ruby', 'Ruby'), ('go', 'Go'), ('swift', 'Swift'), ('kotlin', 'Kotlin'), ('typescript', 'TypeScript'), ('dart', 'Dart'), ('rust', 'Rust'), ('other', 'أخرى')], help_text='لغة البرمجة الرئيسية للمشروع', max_length=20, verbose_name='لغة البرمجة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.IntegerField(default=0, help_text='ترتيب المشروع ضمن المسار', verbose_name='الترتيب')),
                ('course', models.ForeignKey(help_text='المسار التعليمي الذي ينتمي إليه هذا المشروع', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='courses.course', verbose_name='المسار التعليمي')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
                'ordering': ['course', 'order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['course', 'is_active'], name='projects_pr_course__8252d3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['level'], name='projects_pr_level_4bd2cc_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['language'], name='projects_pr_languag_2ccd8c_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('course', 'title'), name='unique_project_title_per_course', violation_error_message='يوجد بالفعل مشروع بهذا العنوان في هذا المسار'),
        ),
    ]
