# Generated by Django 6.0.4 on 2026-04-18 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectstarterfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المهمة')),
                ('description', models.TextField(verbose_name='وصف المهمة')),
                ('task_type', models.CharField(choices=[('text', 'إجابة نصية'), ('code', 'كود برمجي'), ('file', 'رفع ملف')], default='text', max_length=20)),
                ('expected_answer', models.TextField(blank=True, null=True, verbose_name='الإجابة المتوقعة')),
                ('order', models.IntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
