# Generated by Django 6.0.4 on 2026-04-19 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projecttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='hint',
            field=models.TextField(blank=True, null=True, verbose_name='تلميح'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='teaching',
            field=models.TextField(blank=True, null=True, verbose_name='شرح / درس مستفاد'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='expected_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='projecttask',
            constraint=models.UniqueConstraint(fields=('project', 'order'), name='unique_task_order_per_project'),
        ),
    ]
