# Generated by Django 6.0.4 on 2026-04-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_tasksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='last_saved_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Bearbeitung'), ('completed', 'Abgeschlossen')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='admin_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
