# Generated by Django 6.0.4 on 2026-04-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprogress',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات التقييم'),
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='grade_percentage',
            field=models.IntegerField(blank=True, null=True, verbose_name='نسبة الدرجة'),
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='is_graded',
            field=models.BooleanField(default=False, verbose_name='تم التقييم'),
        ),
    ]
