# Generated by Django 6.0.4 on 2026-04-21 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_projectprogress_feedback_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectprogress',
            old_name='grade_percentage',
            new_name='grade_stars',
        ),
    ]
