# Generated by Django 4.2 on 2025-12-17 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='أدخل عنواناً واضحاً ومعبراً للمسار', max_length=200, verbose_name='عنوان المسار')),
                ('description', models.TextField(help_text='أدخل وصفاً مفصلاً للمسار التعليمي', verbose_name='وصف المسار')),
                ('level', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم'), ('expert', 'خبير')], default='beginner', max_length=20, verbose_name='المستوى')),
                ('category', models.CharField(choices=[('web', 'تطوير الويب'), ('mobile', 'تطوير الموبايل'), ('data', 'علوم البيانات'), ('ai', 'الذكاء الاصطناعي'), ('design', 'التصميم'), ('business', 'أعمال'), ('language', 'لغات'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='الفئة')),
                ('estimated_duration', models.IntegerField(help_text='أدخل المدة المقدرة لإتمام المسار بالساعات', verbose_name='المدة المقدرة (بالساعات)')),
                ('projects_count', models.IntegerField(default=0, editable=False, help_text='عدد المشاريع العملية في هذا المسار', verbose_name='عدد المشاريع')),
                ('is_public', models.BooleanField(default=False, help_text='هل هذا المسار متاح للجميع؟', verbose_name='عام للجميع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, help_text='هل هذا المسار نشط أم معطل؟', verbose_name='نشط')),
                ('enrolled_learners', models.ManyToManyField(blank=True, help_text='المتعلمين المنضمين فقط - لا يتم إضافة مشرفين', limit_choices_to={'user_type': 'learner'}, related_name='enrolled_courses_as_learner', to=settings.AUTH_USER_MODEL, verbose_name='المتعلمين المنضمين')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_created', to=settings.AUTH_USER_MODEL, verbose_name='المشرف')),
            ],
            options={
                'verbose_name': 'مسار تعليمي',
                'verbose_name_plural': 'المسارات التعليمية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('title',), name='unique_course_title', violation_error_message='يوجد بالفعل مسار نشط بهذا العنوان في النظام'),
        ),
    ]
